//! Parity harness: replays `tests/fixtures/*.json` (generated by
//! `backend/oracle_dump.py` from the frozen `logic.py` oracle) against the
//! native calc core.
//!
//! Bar: numerics within 1e-9 relative tolerance, exact nulls / strings /
//! statuses. A failure here means the Rust port drifted from the oracle —
//! fix the port, never the fixture (regenerate fixtures only when
//! `logic.py` itself changes, and review that diff).

use std::path::PathBuf;

use beruang_gateway::calc::{
    mutual_fund_returns, stock_returns, term_deposit_returns, CalcError, MutualFundEntry,
    StockEntry, TermDepositEntry,
};
use chrono::NaiveDate;

/// Fixture term-deposit reference date (must match `oracle_dump.py`).
const REFERENCE_DATE: &str = "2026-09-13";
/// Relative epsilon for floats: `|a-b| <= eps * max(1, |a|, |b|)`.
const EPS: f64 = 1e-9;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn approx_eq(expected: f64, actual: f64) -> bool {
    if expected == actual {
        return true;
    }
    if !expected.is_finite() || !actual.is_finite() {
        return false;
    }
    (expected - actual).abs() <= EPS * 1.0_f64.max(expected.abs()).max(actual.abs())
}

fn assert_json_approx(
    fixture: &str,
    path: &str,
    expected: &serde_json::Value,
    actual: &serde_json::Value,
) {
    match (expected, actual) {
        (serde_json::Value::Number(e), serde_json::Value::Number(a)) => {
            let (e, a) = (e.as_f64().unwrap(), a.as_f64().unwrap());
            assert!(approx_eq(e, a), "[{fixture}] {path}: expected {e}, got {a}");
        }
        (serde_json::Value::Array(e), serde_json::Value::Array(a)) => {
            assert_eq!(
                e.len(),
                a.len(),
                "[{fixture}] {path}: array len {} != {}",
                e.len(),
                a.len()
            );
            for (i, (x, y)) in e.iter().zip(a.iter()).enumerate() {
                assert_json_approx(fixture, &format!("{path}[{i}]"), x, y);
            }
        }
        (serde_json::Value::Object(e), serde_json::Value::Object(a)) => {
            for key in e.keys() {
                assert!(
                    a.contains_key(key),
                    "[{fixture}] {path}: missing key '{key}'"
                );
                assert_json_approx(fixture, &format!("{path}.{key}"), &e[key], &a[key]);
            }
            for key in a.keys() {
                assert!(
                    e.contains_key(key),
                    "[{fixture}] {path}: unexpected key '{key}'"
                );
            }
        }
        _ => assert_eq!(
            expected, actual,
            "[{fixture}] {path}: expected {expected}, got {actual}"
        ),
    }
}

fn run_native(asset: &str, payload: &serde_json::Value) -> Result<serde_json::Value, CalcError> {
    match asset {
        "mutual-funds" => {
            let entries: Vec<MutualFundEntry> = serde_json::from_value(payload["entries"].clone())
                .map_err(|e| CalcError::validation(e.to_string()))?;
            mutual_fund_returns(entries).map(|r| serde_json::to_value(r).unwrap())
        }
        "stocks" => {
            let entries: Vec<StockEntry> = serde_json::from_value(payload["entries"].clone())
                .map_err(|e| CalcError::validation(e.to_string()))?;
            stock_returns(entries).map(|r| serde_json::to_value(r).unwrap())
        }
        "term-deposits" => {
            let apy: f64 = serde_json::from_value(payload["apy"].clone())
                .map_err(|e| CalcError::validation(e.to_string()))?;
            let entries: Vec<TermDepositEntry> = serde_json::from_value(payload["entries"].clone())
                .map_err(|e| CalcError::validation(e.to_string()))?;
            let reference = NaiveDate::parse_from_str(REFERENCE_DATE, "%Y-%m-%d").unwrap();
            term_deposit_returns(apy, entries, reference).map(|r| serde_json::to_value(r).unwrap())
        }
        other => panic!("unknown fixture asset '{other}'"),
    }
}

#[test]
fn calc_matches_frozen_oracle() {
    let dir = fixtures_dir();
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".json"))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no fixtures in {}", dir.display());

    for name in &names {
        let fixture: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join(name)).unwrap()).unwrap();
        let asset = fixture["request"]["asset"].as_str().unwrap();
        let payload = &fixture["request"]["payload"];
        let expect = &fixture["expect"];

        match run_native(asset, payload) {
            Ok(actual) => {
                assert_eq!(
                    expect["ok"], true,
                    "[{name}] native succeeded but oracle expects an error"
                );
                assert_json_approx(name, "$", &expect["response"], &actual);
            }
            Err(err) => {
                assert_eq!(
                    expect["ok"], false,
                    "[{name}] native failed ({err}) but oracle expects success"
                );
                assert_eq!(err.status(), 422, "[{name}] wrong status class");
                let needle = expect["detail_contains"].as_str().unwrap();
                assert!(
                    err.detail().contains(needle),
                    "[{name}] detail '{}' missing '{}'",
                    err.detail(),
                    needle
                );
            }
        }
    }
    println!("parity: {} fixtures replayed", names.len());
}
